### ISSUE TITLE
multicodec-packed

### ISSUE THREAD

**Issue by jbenet** [multiformats/multicodec#10]
I just added a PR for multicodec-packed: https://github.com/multiformats/multicodec/pull/9 -- should this be a separate repo or this one? i'm inclined to keep it here (since it's so similar) until it demonstrates the need to move out. other thoughts?

**Comment by diasdavid** [comment]
Let's keep them in the same repo. It is easier to point to :)

**Comment by RichardLitt** [comment]
I would keep it here - it falls under the multicodec heading, still. If needed, we can reopen this later.
