### ISSUE TITLE
sha1 x11 conflict

### ISSUE THREAD

**Issue by Zolmeister** [multiformats/multicodec#115]
sha1 `0x11`
&nbsp; x11   `0x1100`

**Comment by Stebalien** [comment]
* 0x11 = 17
* 0x1100 = 4352

**Comment by Zolmeister** [comment]
so shared byte-prefix is no-conflict

**Comment by Stebalien** [comment]
When necessary, codecs are encoded using base128 varints: https://developers.google.com/protocol-buffers/docs/encoding#varints.
