### ISSUE TITLE
What's the difference between multicodec and multistreams

### ISSUE THREAD

**Issue by tmcw** [multiformats/multicodec#132]
From the multicodec README:

> Multistreams are self-describing protocol/encoding streams.

From the multistream README:

> Multicodecs are self-describing protocol/encoding streams.

Each project has a readme that leads by calling the other project a thing, and they call the projects the same thing.

**Comment by vmx** [comment]
Thanks for the report. Your PR triggered that I will now spend some time on the multiformats stuff to clear things up a bit.

**Comment by vmx** [comment]
Sorry for taking so long, but finally https://github.com/multiformats/multicodec/pull/134 and https://github.com/multiformats/multistream/pull/10 got merged, this should hopefully make things clearer.
