### ISSUE TITLE
Add filecoin hashing functions to table

### ISSUE THREAD

**Issue by mikeal** [multiformats/multicodec#167]
Filecoin is using `raw` CID’s w/ an unregistered multihash function.

https://github.com/filecoin-project/go-fil-commcid/blob/master/commcid.go#L19

We should add this to the table. @Stebalien how should we go about reserving the additional constants noted in the file?

**Comment by Stebalien** [comment]
We got stuck trying to define the right hash functions/formats: https://github.com/multiformats/multicodec/pull/161. We wanted to define some kind of general-purpose "merkle-tree" IPLD format, but at the time, filecoin hadn't even stabilized around how they were hashing content. Has that changed?

**Comment by mikeal** [comment]
They consider the current implementation stable. Any changes to it would cause a pretty massive break across Filecoin.
