### ISSUE TITLE
Dealing with multimedia

### ISSUE THREAD

**Issue by CMCDragonkai** [multiformats/multicodec#168]
How does multicodec deal with multimedia?

Consider mp4 files or mts files. They are container formats. Within each there are choices of audio and video codecs that can be used.

It seems multicodec simply identifying the container format is not powerful enough to describe such files with composite codecs.

**Comment by Stebalien** [comment]
The container format internally records the chosen codecs. Multicodec is enough to remove the initial ambiguity and let us decode the container.

**Comment by CMCDragonkai** [comment]
Has anybody started recording all the multimedia formats into multicodec?

**Comment by Stebalien** [comment]
https://github.com/multiformats/multicodec/pull/159

**Comment by hsanjuan** [comment]
(please close this issue if you considered answered @CMCDragonkai )

**Comment by CMCDragonkai** [comment]
That PR hasn't been merged yet!

**Comment by Stebalien** [comment]
That PR is tracked in #4.

**Comment by hsanjuan** [comment]
Tracking in #4.
