### ISSUE TITLE
Add KangarooTwelve hash?

### ISSUE THREAD

**Issue by tmladek** [multiformats/multicodec#188]
Hello,
I couldn't find the KangarooTwelve hash variant (https://keccak.team/kangarootwelve.html) from the Keccak family, is there a reason it is not included? (Seeing as the rest of the Keccak functions are). Or am I misunderstanding, and it actually does correspond to some of the already included variants?

The reason it's interesting is because it's significantly more performant than the rest of the Keccak functions, and even recommended for such purposes by the Keccak team itself: https://public-inbox.org/git/91a34c5b-7844-3db2-cf29-411df5bcf886@noekeon.org/

Would you consider adding it? Thanks!

**Comment by Stebalien** [comment]
There's no reason not to include it but the major multihash implementations aren't likely to include an implementation of the hash function by default to keep code size down. If you're interested, file a PR and pick a multicodec in the 2-3 byte range. See https://github.com/multiformats/multicodec#adding-new-multicodecs-to-the-table.

OT: Given ever increasing hardware support, I'd generally just suggest sha256 unless you have an issue with length extension attacks.
