### ISSUE TITLE
Java implementation

### ISSUE THREAD

**Issue by richardbergquist** [multiformats/multicodec#284]
Hey - I have a java implementation of the multicodec in my github. I'd be happy to link it to the list of implementations in the readme.md if that would be of help for the multiformat community.  https://github.com/richardbergquist/java-multicodec

I've attempted to submit a PR from a branch, but need permissions to this repo do so. What the process of getting permissions to submit a PR?

Thanks - @richardbergquist

**Comment by rvagg** [comment]
@richardbergquist just fork the repo, push your branch to your fork, then pull request from there - it'll prompt you when you push to your fork so it should be straightfoward from there.

**Comment by richardbergquist** [comment]
Ok, all good - understood now. Have created a very small PR. Thanks. Will close.
