### ISSUE TITLE
Register varsig codes

### ISSUE THREAD

**Issue by Gozala** [multiformats/multicodec#289]
In https://github.com/ucan-wg/ucan-ipld/issues/4 we came to realize that we need self describing signatures for all the same reasons we want self describing hashes a.k.a [multihash](https://github.com/multiformats/multihash)es. 

Intention is to create repo with a `varsig` spec but in the meantime here is the intended format

```
<varint signature algorithm code><varint signature size in bytes><signature in bytes>
```

For that reason we would like to register:

1. codes for relevant signature algorithms
2. code for "varsig" umbrella signature code

Later will be used as secondary tag to enable custom not yet standardized signature algorithms and reduce rate of submissions here.

**Comment by Gozala** [comment]
Also probably we can not use "multisignature" term as it would create confusion with multisigs. Maybe `autosig` would be a better term

**Comment by rvagg** [comment]
sgtm

**Comment by expede** [comment]
@Gozala with #290 merged, is there more to do in this Issue?

**Comment by rvagg** [comment]
@Gozala got a plan for moving forward with this? Do you need a place for this, do you want a new repo or can we find a home in an existing repo. Multibase has an `rfcs` directory for "spec-like" things: https://github.com/multiformats/multibase/tree/master/rfcs, perhaps we could do something like that in one of the other multiformats repos?

**Comment by Gozala** [comment]
> @Gozala got a plan for moving forward with this? Do you need a place for this, do you want a new repo or can we find a home in an existing repo. Multibase has an `rfcs` directory for "spec-like" things: https://github.com/multiformats/multibase/tree/master/rfcs, perhaps we could do something like that in one of the other multiformats repos?

This is already used by dag-ucan

https://github.com/ucan-wg/ucan-ipld/
https://github.com/ipld/js-dag-ucan

And there is an ongoing effort to spec out details here https://github.com/ChainAgnostic/varsig

**Comment by Gozala** [comment]
Closing because PR with added codes had been merged
