### ISSUE TITLE
Rust implementation?

### ISSUE THREAD

**Issue by TheButlah** [multiformats/multicodec#335]
What is the preferred crate to use for a rust implementation of multicodec? I found [this](https://github.com/gnunicorn/rust-multicodec) but it looked abandoned.

**Comment by mxinden** [comment]
In the Rust ecosystem `multicodec`'s are used directly in their dependent crates:

- https://github.com/multiformats/rust-multiaddr
- https://github.com/multiformats/rust-multihash/
- https://github.com/multiformats/rust-cid

Let me know if this helps @TheButlah.
