### ISSUE TITLE
`es512` Varsig codec name is incorrect

### ISSUE THREAD

**Issue by dhuseby** [multiformats/multicodec#349]
This is an error:
https://github.com/multiformats/multicodec/blob/c954a787dc6a17d099653e5f90d26fbd177d2074/table.csv#L540

The name should be `es521` because this is an ECDSA signature using the P-521 curve.

**Comment by smoyer64** [comment]
ES512 is the correct algorithm name: https://datatracker.ietf.org/doc/html/rfc7518#section-3.1

**Comment by rvagg** [comment]
So, named after the hash algorithm, so 512 is correct. Thanks for jumping in @smoyer64.

**Comment by dhuseby** [comment]
Aha! Thanks for clarifying. That was confusing. Cheers! 🍻
