### ISSUE TITLE
json missing from table.csv

### ISSUE THREAD

**Issue by zippy** [multiformats/multicodec#36]
Hi, I'm trying to figure out why some values in the table.csv have codes and others don't, and why it includes bson but not json when json is clearly implemented (at least as far as I can see in the go-multicodec repo).  Can someone enlighten me?  Thanks!

**Comment by hsanjuan** [comment]
According to https://github.com/multiformats/go-multicodec/pull/20#issuecomment-274663160, protocol codes are for multicodec-packed. That is (I think), when the encoded messages are preceded by a code identifying their format. Perhaps @lgierth can provide more info, but my guess is that if it does not have a code is because it is not used as a self-describing codec.

**Comment by jmcph4** [comment]
@hsanjuan I know this is now quite an old issue, but I am working on my own implementation over at [jmcph4/azorian](https://github.com/jmcph4/azorian) and I've encountered similar issues as OP and I still don't understand why some protocols are listed but specified without complete values (i.e. just `0x`).

**Comment by Stebalien** [comment]
Which part are you trying to implement?

**Comment by jmcph4** [comment]
@Stebalien From my understanding, `table.csv` contains the standard table for multicodec values, so I'm currently trying to write macro definitions for them. This is to allow users to write something like this:

    /* my_multicodec_value now evaluates to 0xb240 */
    az_multicodec_t my_multicodec_value = AZ_MULTICODEC_BLAKE2B_512;

Two main issues, although I can mostly solve the latter:

1. Some entries in the table are missing valid values (i.e. `0x`)
2. Frequent and/or arbitrary changes to the standard table at any time

**Comment by Stebalien** [comment]
1. This is to indicate that we plan on defining the code but haven't yet (mostly as examples for different types of content). However, I've gone ahead and filed issues for them and removed them from the actual table (you're not the first to find this annoying).
2. Hopefully this'll calm down. Most of these changes have been to fix inconsistencies both within this table and between this table and other multiformats tables.

**Comment by jmcph4** [comment]
@Stebalien Good to hear that upstream is aware of this! I'm also glad to hear I'm not the only implementor encountering difficulties - lets me know I'm not doing anything wrong.

**Comment by Stebalien** [comment]
fixed in https://github.com/multiformats/multicodec/pull/141.
