### ISSUE TITLE
Clean up table

### ISSUE THREAD

**Issue by jbenet** [multiformats/multicodec#38]
The table is messy. we should:

- [ ] remove, or separate out, all entries that do not yet have a code assigned
- [ ] keep it sorted by code

**Comment by lgierth** [comment]
- [ ] move code to first column, description to last
- [ ] fix comment -- with the current column order, they should be `,mycomment,`, not `mycomment,,`
- [ ] find a simple csv linter tool

Is this thing already being parsed by something? Otherwise let's do this relatively asap.

**Comment by Kubuxu** [comment]
Assign code type, so it is possible to automatically extract only codes from multihash.

It could be word tag, we could make it possible to assign multiple tags by joining them with `+` or something.

**Comment by Kubuxu** [comment]
Very simple viewer page (on IPFS for example) would be awesome. It could show byte number ranges(0-127, 128-32767), taken and free spots.

**Comment by chrisdostert** [comment]
This table... my OCD.. ahhh! 
Also possibly w/ this cleanup effort could we formalize how codes are determined? It seems sometimes random, sometimes following a pattern (maybe i'm missing something). 

A simple idea would be to just go in ascending order of available codes from now on or something to that effect.

**Comment by Kubuxu** [comment]
@chrisdostert primary reason for codes seeming random is that we use varint. We want to reserve one byte or two byte codes for future protocols that might need a code.
Then there is assigning code corresponding to ports, or hex-like-name (`0xb2XX` for blake2 or `0xed` for ed25519).

**Comment by chrisdostert** [comment]
@Kubuxu Wouldn't it just be easier (& deterministic) if we simply assigned a code in ascending order (or something) based on when each was added to the table? 

Why try to partially arrange them? Seems like it's futile as there will likely eventually need to be exceptions anyways as time goes on and we end up w/ these sparse assignments all over the code space.

**Comment by Kubuxu** [comment]
Because we want codes that will be used in content addressing data to be just one byte. A code for obscure protocol or some weird pub-key crypto may be longer as it won't be used as much.

**Comment by vmx** [comment]
I'd like to revive this issue. As more and more people want to add codecs, it becomes harder and harder with the current table.

I propose (based on the comments here and open PRs):

 - Get rid of the "headlines" we currently have, e.g. "serialization formats" or "multihashes"
 - Introduce a new column called "category". The values will be what previously were "headlines". This way you can easily sort by those if you want to.
 - Re-order columns to: code, codec, description, category
 - Sort by code. Currently the hardest part about adding a new codec is to find a free spot.

@Stebalien @jbenet What do you think?

**Comment by Stebalien** [comment]
That sounds like a great solution. My main concern is that github doesn't *provide* a way to sort but we can probably find a work around.

**Comment by vmx** [comment]
This issue was fixed by https://github.com/multiformats/multicodec/commit/942b8875da24b2c60ecb0eb87c9b81e92d8f595c, hence closing it.
