### ISSUE TITLE
The udp code is wrong

### ISSUE THREAD

**Issue by Stebalien** [multiformats/multicodec#51]
According to the multiaddr repo, the code for udp is 0x011. However, in this repo, it's 0x0111. Unfortunately, sha1 is 0x011 here...

Also, some of these numbers appear to be varint encodes, others not?

**Comment by Stebalien** [comment]
@lgierth,

@whyrusleeping told me to ask you about this.

**Comment by Stebalien** [comment]
Also,

/cc @vyzo

**Comment by vyzo** [comment]
The ipfs code for multiaddr is wrong too, it's 0x2A which decodes to 42, not 421 (the actual P_IPFS multiaddr code).

**Comment by Kubuxu** [comment]
From what  I can recall: This is an issue that arose when we were unifying multihash, multiaddr and multicodec.

UDP got was conflicting with SHA1 but as it is not used in the network it was moved.
Not sure what is going on with IPFS code.

**Comment by Stebalien** [comment]
> UDP got was conflicting with SHA1 but as it is not used in the network it was moved.

Do you have any idea what might break if we fix https://github.com/multiformats/go-multiaddr/blob/22c78388e24432a438493c1f61c1edda49099e80/protocols.go#L26?

**Comment by lgierth** [comment]
Fix it -- udp isn't used anywhere currently. The only use was the now-defunct UTP transport.

**Comment by lgierth** [comment]
And while we're on it, let's finally centralize the codec table and remove it in all other repos. This issue keeps happening where codes diverge, and we can't have that

**Comment by Stebalien** [comment]
Good point. Do you mind if I call it `go-mc-table`?

FYI, UDT/UTP are also flipped. Is the multicodec repo the source of truth?

**Comment by lgierth** [comment]
Yeah the table here in multicodec.git is the source of truth -- no need to have a separate go-table package though?

**Comment by lgierth** [comment]
> FYI, UDT/UTP are also flipped

UDT is fine to fix right away too, we never got to a working transport there. For other things we might need to look closer.

**Comment by Stebalien** [comment]
> no need to have a separate go-table package though?

Otherwise we're left with magic constants distributed throughout random packages that may or may not match up with a single source of truth.

**Comment by lgierth** [comment]
Mh yeah... what about having the go and js data structures for this along with the table in one repo?

**Comment by Stebalien** [comment]
I'm worried that some language-specific package managers may not play well with that.

**Comment by Stebalien** [comment]
@vyzo, you claimed that some of these appear to be varint encoded. Which ones?

**Comment by vyzo** [comment]
I think that was my mistake by eyeballing, it doesn't appear to be the case with double checking.
