### ISSUE TITLE
Quic and CBOR have the same multicodec

### ISSUE THREAD

**Issue by Stebalien** [multiformats/multicodec#55]
Both use 0x51 (OT: this also also happens to be 'Q' the base58btc encoding of 0x12, the SHA2-256 multicodec and the prefix of all of our v0 CIDs).

**Comment by lgierth** [comment]
Let's give QUIC a new code as CBOR is already in use in quite a few places. `Q` is fine, we only need to watch out not to produce `Qm` stuff of a specific length.
